# Generated by Django 2.0.5 on 2018-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', help_text="User's full name", max_length=255, verbose_name='Name'),
        ),
    ]
