# Generated by Django 2.0.7 on 2018-07-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0007_auto_20180705_1633'),
        ('ej_users', '0002_auto_20180529_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_conversations',
            field=models.ManyToManyField(to='ej_conversations.Conversation'),
        ),
    ]
