# Generated by Django 2.0.8 on 2018-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ej_users', '0002_create_password_token_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='url',
            field=models.CharField(max_length=50, unique=True, verbose_name='User token'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name'
        ),
    ]
