# Generated by Django 2.0.6 on 2018-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0008_auto_20180722_2258'),
        ('ej_users', '0003_user_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_conversations',
            field=models.ManyToManyField(to='ej_conversations.Conversation'),
        ),
    ]
