# Generated by Django 2.0.6 on 2018-06-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0002_auto_20180620_0326'),
        ('ej_users', '0003_auto_20180620_0326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMissions',
            new_name='UserMission',
        ),
    ]
