# Generated by Django 2.2.19 on 2021-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0003_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(choices=[('listen_to_community', 'Listen to community')], default='listen_to_community', help_text='User signature', max_length=50, verbose_name='Signature'),
        ),
    ]
