# Generated by Django 2.0.6 on 2018-07-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0004_auto_20180723_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='board_name',
        ),
    ]
