# Generated by Django 3.2 on 2022-07-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0005_alter_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(choices=[('listen_to_community', 'Listen to community'), ('listen_to_city', 'Listen to city'), ('listen_to_city_yearly', 'Listen to city yearly')], default='listen_to_community', help_text='User signature', max_length=50, verbose_name='Signature'),
        ),
    ]
