# Generated by Django 2.0.7 on 2018-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0005_remove_user_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_conversations',
        ),
    ]
