# Generated by Django 2.0.7 on 2018-07-30 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0008_merge_20180709_1915'),
        ('ej_users', '0005_auto_20180625_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversations', models.ManyToManyField(blank=True, to='ej_conversations.Conversation')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
