# Generated by Django 2.1.7 on 2019-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0005_auto_20190201_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name used to publicly identify user', max_length=50),
        ),
    ]
