# Generated by Django 2.0.7 on 2018-07-30 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0006_userconversations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversations',
            name='users',
        ),
        migrations.AddField(
            model_name='userconversations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
