# Generated by Django 2.1.7 on 2019-03-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0006_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='limit_board_conversations',
        ),
    ]
