# Generated by Django 2.0.7 on 2018-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_users', '0009_auto_20180803_2203'),
        ('ej_users', '0003_auto_20180725_1909'),
    ]

    operations = [
    ]
