# Generated by Django 2.0.7 on 2018-08-07 20:23

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='candidacy',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='senadora', help_text='the candadite candidacy', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='party',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pt', help_text='The candidate party initials', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='urn',
            field=models.IntegerField(help_text='The candidate urn number'),
        ),
    ]
