# Generated by Django 2.0.7 on 2018-08-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0003_auto_20180807_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='candidates'),
        ),
    ]
