# Generated by Django 2.0.7 on 2018-08-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0004_candidate_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
