# Generated by Django 2.0.7 on 2018-08-07 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_candidates', '0006_candidate_selectedcandidates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedCandidates',
            new_name='SelectedCandidate',
        ),
    ]
