# Generated by Django 2.0.7 on 2018-08-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0008_pressedcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='adhered_to_the_measures',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='committed_to_democracy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='has_clean_pass',
            field=models.BooleanField(default=True),
        ),
    ]
