# Generated by Django 2.0.6 on 2018-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0011_ignoredcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='external_page',
            field=models.CharField(default='', help_text='The site of the candidate', max_length=100),
        ),
    ]
