# Generated by Django 2.0.6 on 2018-08-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0012_candidate_external_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='external_page',
            new_name='site_url',
        ),
    ]
