# Generated by Django 2.0.7 on 2018-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0014_auto_20180813_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(default='card_avatar-default.png', upload_to='candidates'),
        ),
    ]
