# Generated by Django 2.0.7 on 2018-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0015_auto_20180813_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='public_email',
            field=models.CharField(default='test@mail.com', help_text='The public email of the candidate', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='crowdfunding_url',
            field=models.CharField(blank=True, help_text='The candidate crowdfunding', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebook_url',
            field=models.CharField(blank=True, help_text='The candidate facebook page', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='instagram_url',
            field=models.CharField(blank=True, help_text='The candidate instagram page', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter_url',
            field=models.CharField(blank=True, help_text='The candidate twitter page', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='The candidate instagram page', max_length=30),
        ),
    ]
