# Generated by Django 2.0.7 on 2018-08-22 15:11

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0016_auto_20180815_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='adhered_to_the_measures',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='SIM', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidacy',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='SENADOR(A)', help_text='the candadite candidacy', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='committed_to_democracy',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='SIM', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='crowdfunding_url',
            field=models.CharField(default='', help_text='The candidate crowdfunding', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebook_url',
            field=models.CharField(default='', help_text='The candidate facebook page', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='has_clean_pass',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='SIM', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='instagram_url',
            field=models.CharField(default='', help_text='The candidate instagram page', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='PT', help_text='The candidate party initials', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='public_email',
            field=models.CharField(default='ricardo@cidadedemocratica.org.br', help_text='The candidate public email', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter_url',
            field=models.CharField(default='', help_text='The candidate facebook page', max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='uf',
            field=models.CharField(default='', help_text='The candidate uf', max_length=2),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='youtube_url',
            field=models.CharField(default='', help_text='The candidate instagram page', max_length=60),
        ),
    ]
