# Generated by Django 2.0.7 on 2018-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0017_auto_20180822_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', help_text='The full name of the candidate', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='justify_adhered_to_the_measures',
            field=models.CharField(default='', help_text='Justification from the candidate', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lawsuits',
            field=models.CharField(default='', help_text='Candidate lawsuits', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='occupation',
            field=models.CharField(default='', help_text='The occupation of the candidate', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='riches',
            field=models.CharField(default='', help_text='Candidate riches', max_length=500),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(help_text='The urn name of the candidate', max_length=100),
        ),
    ]
