# Generated by Django 2.0.5 on 2018-05-28 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej_conversations', '0003_auto_20180528_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationPowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_comments', models.PositiveSmallIntegerField()),
                ('endorsed_comments', models.PositiveSmallIntegerField()),
                ('endorsement_actions', models.PositiveSmallIntegerField()),
                ('can_be_clusterized', models.BooleanField(default=False)),
                ('can_see_cluster_names', models.BooleanField(default=False)),
                ('can_see_divergence_distribution', models.BooleanField(default=False)),
                ('can_see_vote_predictions', models.BooleanField(default=False)),
                ('has_created_comment', models.BooleanField(default=False)),
                ('has_voted_all_comments', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndorsementRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('any', 'Any comment in conversation'), ('self', 'Self promotion'), ('other', 'Endorse comment from other user'), ('group', "Endorse comment from a user in the user's cluster"), ('other_group', 'Endorse comment from user from a different cluster')], default='any', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='conversationpowers',
            unique_together={('user', 'conversation')},
        ),
        migrations.AlterUniqueTogether(
            name='commentendorsement',
            unique_together={('comment', 'user')},
        ),
    ]
