# Generated by Django 2.2.19 on 2021-09-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej_conversations', '0013_auto_20210901_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(help_text='The domain that the rasa bot webchat is hosted.', max_length=255, verbose_name='Domain')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasa_conversations', to='ej_conversations.Conversation')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('conversation', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='ConversationMautic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
                ('access_token', models.CharField(blank=True, max_length=200, verbose_name='Mautic Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=200, verbose_name='Refresh Token')),
                ('url', models.URLField(help_text='Generated Url from Mautic.', max_length=255, verbose_name='Mautic URL')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mautic_integration', to='ej_conversations.Conversation')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('conversation', 'url')},
            },
        ),
    ]
