# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_auto_20180111_1403'),
        ('math', '0002_auto_20180116_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='argument',
        ),
        migrations.AddField(
            model_name='job',
            name='conversation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='math_jobs', to='conversations.Conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
