# Generated by Django 2.0.6 on 2018-07-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej_channels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('channel', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ej_channels.Channel')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
