# Generated by Django 2.0.6 on 2018-07-23 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_messages', '0002_auto_20180723_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ej_channels.Channel'),
        ),
    ]
