# Generated by Django 2.0.6 on 2018-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_messages', '0003_auto_20180723_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
