# Generated by Django 2.0.6 on 2018-07-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_messages', '0004_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
