# Generated by Django 2.0 on 2018-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPallete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('material_icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material_icon')),
                ('fa_icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='FA_icon')),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name='Priority')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
            ],
        ),
    ]
