# Generated by Django 2.0 on 2018-04-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('format', models.CharField(max_length=4)),
                ('editable', models.BooleanField(default=True)),
                ('deletable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FragmentLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock', to='configurations.Fragment')),
            ],
        ),
    ]
