# Generated by Django 2.0.4 on 2018-04-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_fragment_fragmentlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='content',
            field=models.TextField(blank=True, help_text='The fragment content in html or markdown that will be displayed', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='deletable',
            field=models.BooleanField(default=True, help_text='Boolean if its possible to delete this fragment'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='editable',
            field=models.BooleanField(default=True, help_text='Boolean if the fragment its editable after being saved in db'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='format',
            field=models.CharField(help_text='Format of the saved fragment, can be html or md', max_length=4),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the fragment to help identify some page part.', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
