# Generated by Django 2.0.4 on 2018-04-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20180426_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaIcon',
        ),
    ]
