# Generated by Django 2.0.4 on 2018-04-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_delete_socialmediaicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(help_text='Name of the social network', max_length=50, unique=True, verbose_name='Social network')),
                ('icon_name', models.CharField(help_text='Icon name for the icon font', max_length=50, verbose_name='Icon name')),
                ('icon_font', models.CharField(default='fa', max_length=10, verbose_name='Icon font')),
                ('ordering', models.PositiveSmallIntegerField(help_text='You must manually define the ordering that each icon should appear in the interface.', unique=True, verbose_name='Ordering')),
                ('url', models.URLField(help_text='Link to your social account page.', verbose_name='URL')),
            ],
        ),
    ]
