# Generated by Django 2.0 on 2018-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_socialmediaicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaicon',
            options={'ordering': ['index', 'id']},
        ),
        migrations.RemoveField(
            model_name='socialmediaicon',
            name='icon_font',
        ),
        migrations.RemoveField(
            model_name='socialmediaicon',
            name='ordering',
        ),
        migrations.AddField(
            model_name='socialmediaicon',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, help_text='You can manually define the ordering that each icon should appear in the interface. Otherwise, icons will be shown in insertion order.', verbose_name='Ordering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fragment',
            name='format',
            field=models.CharField(choices=[('html', 'HTML'), ('md', 'Markdown')], help_text='Format of the saved fragment, can be either HTML or Markdown', max_length=4),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='icon_name',
            field=models.CharField(help_text='Icon name in font-awesome', max_length=50, verbose_name='Icon name'),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='social_network',
            field=models.CharField(help_text='Name of the social network (e.g., Facebook)', max_length=50, unique=True, verbose_name='Social network'),
        ),
    ]
