# Generated by Django 2.0 on 2018-04-30 00:25

from django.db import migrations, models
import ej.configurations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20180429_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediaicon',
            options={'ordering': ['index', 'id'], 'verbose_name': 'Social media icon', 'verbose_name_plural': 'Social media icons'},
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='deletable',
        ),
        migrations.AlterField(
            model_name='fragment',
            name='content',
            field=models.TextField(blank=True, help_text='Raw fragment content in HTML or Markdown', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='editable',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='format',
            field=models.CharField(choices=[('html', 'HTML'), ('md', 'Markdown')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='name',
            field=models.CharField(db_index=True, help_text='Unique identifier for fragment name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='icon_name',
            field=models.CharField(help_text='Icon name in font-awesome', max_length=50, validators=[ej.configurations.validators.validate_icon_name], verbose_name='Icon name'),
        ),
    ]
