# Generated by Django 2.0 on 2018-05-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20180429_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentlock',
            name='fragment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lock_ref', to='configurations.Fragment'),
        ),
    ]
