# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20171010_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.CharField(choices=[('AP', 'Approved'), ('RE', 'Rejected'), ('UN', 'Unmoderated')], max_length=2, null=True),
        ),
    ]
