# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_auto_20171024_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='polis_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Polis slug'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='polis_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Polis url'),
        ),
    ]
