# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_auto_20171101_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='comment_nudge_global_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
