# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_auto_20171109_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Is new'),
        ),
    ]
