# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0015_auto_20171207_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='opinion',
            field=models.TextField(blank=True, null=True, verbose_name='Our Opinion'),
        ),
    ]
