# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 16:51
from __future__ import unicode_literals

import autoslug.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ej.conversations.models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0018_auto_20180208_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', slugify=ej.conversations.models.custom_slugify, unique=True)),
                ('styles', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Styles')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversations/categories', verbose_name='Image')),
                ('image_caption', models.CharField(blank=True, max_length=255, verbose_name='Image caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.Category'),
        ),
    ]
