# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0021_add_category_options'),
    ]

    operations = [
        migrations.RenameField('category', 'styles','customizations')
    ]
