# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20171011_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='comment',
            name='approval',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('UNMODERATED', 'unmoderated')], default='UNMODERATED', max_length=32),
            preserve_default=False,
        ),
    ]
