# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_conversation_comment_nudge_global_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approval',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('UNMODERATED', 'unmoderated')], default='UNMODERATED', max_length=32),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='conversations/backgrounds'),
        ),
    ]
