# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import pushtogether.conversations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_auto_20171101_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='approval',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('UNMODERATED', 'unmoderated')], default='UNMODERATED', max_length=32, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='polis_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Polis id'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[pushtogether.conversations.validators.validate_color], verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='conversations/backgrounds', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='comment_nudge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comment nudge'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='comment_nudge_global_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comment nudge global limit'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='comment_nudge_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comment nudge interval'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='dialog',
            field=models.TextField(blank=True, null=True, verbose_name='Dialog'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='polis_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Polis id'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Respose'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='polis_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Polis id'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(1, 'AGREE'), (0, 'PASS'), (-1, 'DISAGREE')], verbose_name='Value'),
        ),
    ]
