# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_conversation_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection reason'),
        ),
    ]
