# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_comment_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Response'),
        ),
    ]
