# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 16:03
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import pushtogether.conversations.models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0016_auto_20171214_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', slugify=pushtogether.conversations.models.custom_slugify, unique=True),
        ),
    ]
