# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0017_auto_20180111_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promoted'),
        ),
    ]
