# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
from autoslug import AutoSlugField
from autoslug.settings import slugify as default_slugify
import jsonfield

def custom_slugify(value):
    return default_slugify(value).lower()

class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0018_auto_20180208_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, blank=False)),
                ('slug', AutoSlugField(null=True, default=None, editable=False, populate_from='name', unique=True, slugify=custom_slugify)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conversations/categories', verbose_name='Image')),
                ('styles', jsonfield.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.ForeignKey(related_name='conversations', to='conversations.Category', null=True),
        ),
    ]
