# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0019_auto_20180219_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.Category'),
        ),
    ]
