# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0020_auto_20180223_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_tour',
            field=models.BooleanField(default=True, verbose_name='Has User Tour'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_login_required',
            field=models.BooleanField(default=True, verbose_name='Is Login Required'),
        ),
    ]
