# Generated by Django 2.0.8 on 2018-10-11 01:55

from django.db import migrations, models
import ej_configurations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ej_configurations', '0001_first_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaicon',
            name='icon_name',
            field=models.CharField(help_text='Icon name in font-awesome. Use short version like "google", "facebook-f", etc.', max_length=50, validators=[ej_configurations.validators.validate_icon_name], verbose_name='Icon name'),
        ),
    ]
