# Generated by Django 2.0.6 on 2018-07-04 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_trophies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'trophies'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'verbose_name_plural': 'user trophies'},
        ),
        migrations.AlterField(
            model_name='trophy',
            name='complete_on_required_satisfied',
            field=models.BooleanField(default=False, help_text='If set as True and the trophy has required trophies associated with, the completeness will be established automatically after all requirementes satisfied', verbose_name='complete on requirements satisfied?'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='required_trophies',
            field=models.ManyToManyField(blank=True, to='ej_trophies.Trophy', verbose_name='required trophies'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='score_completed',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='score for completion'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='score_percent',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='score for each percent of completion'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='users',
            field=models.ManyToManyField(blank=True, through='ej_trophies.UserTrophy', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='notified',
            field=models.BooleanField(default=False, help_text='temporary field to track if the user saw the notification or not', verbose_name='notified?'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='percentage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentage of progress'),
        ),
    ]
