# Generated by Django 2.0.6 on 2018-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_trophies', '0002_auto_20180704_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': 'trophy', 'verbose_name_plural': 'trophies'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'verbose_name': "user's trophy", 'verbose_name_plural': "user's trophies"},
        ),
        migrations.AlterField(
            model_name='trophy',
            name='full_description',
            field=models.TextField(blank=True, help_text='Explain all the steps to achieve this trophy and additional infos', verbose_name='full description'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='short_description',
            field=models.CharField(blank=True, help_text='Explain the general steps to achieve this trophy', max_length=50, verbose_name='short description'),
        ),
    ]
