# Generated by Django 2.0.6 on 2018-07-04 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_trophies', '0003_auto_20180704_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrophy',
            name='trophy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_trophies.Trophy', verbose_name='trophy'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
