# Generated by Django 2.0.6 on 2018-07-04 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_trophies', '0004_auto_20180704_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If set as False, the trophy will not be synced with users', verbose_name='is active?'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='reference_link',
            field=models.URLField(blank=True, help_text='A general reference link. Example: A link to the page which the trophy can be earned', verbose_name='reference link'),
        ),
        migrations.AlterField(
            model_name='usertrophy',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentage of progress'),
        ),
    ]
