# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 19:02
from __future__ import unicode_literals
from pinax.points.models import PointValue
from django.db import migrations
from django.db import transaction


@transaction.atomic
def forwards_func(apps, schema_editor):
   # PointValue = apps.get_model('pinax.points', 'PointValue')
   db_alias = schema_editor.connection.alias
   PointValue.objects.using(db_alias).bulk_create([
       PointValue(key="comment_approved", value="10"),
       PointValue(key="user_created", value="100"),
       PointValue(key="user_profile_filled", value="200"),
       PointValue(key="voted", value="10"),
       PointValue(key="voted_first_time_in_second_conversation", value="100"),
       PointValue(key="voted_first_time_in_new_conversation_after_second", value="50"),
   ])

@transaction.atomic
def reverse_func(apps, schema_editor):
    # PointValue = apps.get_model('pinax.points', 'PointValue')
    db_alias = schema_editor.connection.alias
    PointValue.objects.using(db_alias).filter(key="comment_approved", value="10").delete()
    PointValue.objects.using(db_alias).filter(key="user_created", value="100").delete()
    PointValue.objects.using(db_alias).filter(key="user_profile_filled", value="200").delete()
    PointValue.objects.using(db_alias).filter(key="voted", value="10").delete()
    PointValue.objects.using(db_alias).filter(key="voted_first_time_in_second_conversation", value="100").delete()
    PointValue.objects.using(db_alias).filter(key="voted_first_time_in_new_conversation_after_second", value="50").delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
