# Generated by Django 2.0.6 on 2018-08-19 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ej_boards.validators
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ej_conversations", "0001_first_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text='Short text used to identify the board URL (e.g.: "johns-board")',
                        unique=True,
                        validators=[ej_boards.validators.validate_board_slug],
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Board", "verbose_name_plural": "Boards"},
        ),
        migrations.CreateModel(
            name="BoardSubscription",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="board_subscriptions",
                        serialize=False,
                        to="ej_conversations.Conversation",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_subscriptions",
                        to="ej_boards.Board",
                    ),
                ),
            ],
        ),
    ]
