# Generated by Django 2.2.2 on 2019-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("ej_boards", "0001_initial"), ("ej_conversations", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="board",
            name="conversations",
            field=models.ManyToManyField(
                blank=True, related_name="boards", to="ej_conversations.Conversation"
            ),
        )
    ]
