# Generated by Django 2.2.19 on 2021-08-02 20:39

from django.db import migrations
from django.utils.text import slugify
from django.db import transaction
from django.utils.translation import gettext_lazy as _


def create_default_board(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Users = apps.get_model("ej_users", "User")
    Boards = apps.get_model("ej_boards", "Board")

    for user in Users.objects.all():
        if user_not_have_default_board(user):
            create_user_default_board(user, db_alias, Boards)


def user_not_have_default_board(user):
    return not (slugify(user.email[:50]),) in list(user.boards.values_list("slug"))


def create_user_default_board(user, db_alias, Boards):
    try:
        with transaction.atomic():
            default_board = Boards.objects.using(db_alias).create(
                slug=slugify(user.email[:50]),
                owner=user,
                title=_("My Board"),
                description="Default user board",
                palette="brand",
            )
            add_conversations_to_default_board(user, db_alias, default_board)
    except Exception as e:
        print(e)


def add_conversations_to_default_board(user, db_alias, default_board):
    for conversation in user.conversations.all():
        try:
            with transaction.atomic():
                if conversation.boards.count() == 0:
                    conversation.boards.add(default_board)
        except Exception as e:
            print(e)


class Migration(migrations.Migration):

    dependencies = [
        ("ej_boards", "0002_barbara_rc1"),
    ]

    operations = [migrations.RunPython(create_default_board)]
