# Generated by Django 2.1.3 on 2018-12-21 17:25

import django.core.validators
from django.db import migrations, models
import ej_boards.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ej_boards', '0003_board_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='board',
            name='sub_domain',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Domain', regex='\\w{3}.?[a-z]+\\.[a-z]+'), ej_boards.validators.validate_sub_domain], verbose_name='SubDomain used to access the board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='palette',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple')], default='Blue', max_length=10, verbose_name='Palette'),
        ),
    ]
