# Generated by Django 2.2.19 on 2021-09-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_boards', '0004_set_board_on_conversations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='conversations',
        ),
    ]
