# Generated by Django 3.2 on 2022-05-16 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_boards', '0005_remove_board_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='users_favorite',
            field=models.ManyToManyField(default=[], related_name='favorite_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
