ARG ORG=ej
FROM ${ORG}/web:base

# Copy files
COPY --chown=django:django ./.coveragerc /app/
COPY --chown=django:django ./*.py /app/
COPY --chown=django:django ./*.rst /app/
COPY --chown=django:django ./etc/ /app/etc/
COPY --chown=django:django ./docs/ /app/docs
COPY --chown=django:django ./locale/ /app/locale/
COPY --chown=django:django ./lib/themes/ /app/lib/themes/
COPY --chown=django:django ./lib/js/ /app/lib/js/
COPY --chown=django:django ./lib/scss/ /app/lib/scss/
COPY --chown=django:django ./lib/assets/ /app/lib/assets/
COPY --chown=django:django ./src/ /app/src/

# Rocket.Chat integration
ARG ROCKETCHAT=false
ENV EJ_ROCKETCHAT_INTEGRATION=${ROCKETCHAT}

# Prepare assets
USER django
RUN mkdir -p local/logs local/static/ local/media/ local/db/ lib/build/ \
 && inv -e sass -t ${EJ_THEME} js docs i18n -c \
 && EJ_THEME=${EJ_THEME} python manage.py collectstatic --noinput \
 && chown django:django /app/local/* -R \
 && echo "COLLECTED STATIC ASSETS"

# Default command
CMD ["db", "-m", "gunicorn"]
