ARG ORG=ej
FROM ${ORG}/web:base

# Copy files
COPY ./.coveragerc /app/
COPY ./manage.py /app/
COPY ./docs/ /app/docs
COPY ./lib/ /app/lib/
COPY ./src/ /app/src/
COPY ./locale/ /app/locale/

# Prepare assets
RUN mkdir -p local/logs local/static/ local/media/ local/db/ \
 && python manage.py collectstatic --noinput \
 && inv -e docs \
 && inv -e js \
 && inv -e sass \
 && echo "COLLECTED STATIC ASSETS"

# Default command
CMD ["db", "-m", "gunicorn"]
