ARG BASE_IMAGE=ejplatform/web:latest
FROM $BASE_IMAGE as django
FROM nginx:1.13

COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=django /app/local/static/ /usr/share/nginx/html/static/
