# Generated by Django 2.0.6 on 2018-07-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0027_mission_conversations'),
        ('ej_notifications', '0002_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ej_missions.Mission'),
        ),
    ]
