# Generated by Django 2.0.6 on 2018-07-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_notifications', '0003_notification_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='mission',
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
