# Generated by Django 2.0.6 on 2018-07-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_notifications', '0004_auto_20180726_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
    ]
