# Generated by Django 2.0 on 2018-04-23 14:56

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import ej.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Occupation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Image')),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('CIS_FEMALE', 'Cis Female'), ('CIS_MALE', 'Cis Male'), ('AGENDER', 'Agender'), ('GENDERQUEER', 'Genderqueer'), ('GENDERFLUID', 'Genderfluid'), ('NON-CONFORMIST_GENDER', 'Non conformist gender'), ('VARIANT_GENDER', 'Variant gender'), ('INTERSEX', 'Intersex'), ('NON-BINARY', 'Non binary'), ('TRANSGENDERED', 'Transgendered'), ('PANGENDER', 'Pangender'), ('TRANSSEXUAL_WOMAN', 'Transsexual woman'), ('TRANSSEXUAL_MAN', 'Transsexual man'), ('TRANSFEMINAL', 'Transfeminal'), ('TRANSMASCULINE', 'Transmasculine'), ('DO_NOT_KNOW', 'Do not know'), ('NONE', 'None'), ('OTHER', 'Other')], max_length=255, null=True, verbose_name='Gender identity')),
                ('gender_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='User provided gender')),
                ('political_movement', models.TextField(blank=True, max_length=255, null=True, verbose_name='Political activity')),
                ('race', models.CharField(blank=True, choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('INDIGENOUS', 'Indigenous'), ('DO_NOT_KNOW', 'Do not know'), ('UNDECLARED', 'Undeclared')], max_length=255, null=True, verbose_name='Race')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', ej.users.models.UserManager()),
            ],
        ),
    ]
