# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:10
from __future__ import unicode_literals

from django.db import migrations, models
from ..models import User

def migrate_data_forward(apps, schema_editor):
    for instance in User.objects.all():
        instance.tour_step = 'STEP_FINISH'
        instance.save()

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_tour_step'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
