# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180111_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User provided gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='political_movement',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Political activity'),
        ),
    ]
