# Generated by Django 2.2.19 on 2021-07-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej_conversations', '0007_auto_20210330_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='ej_conversations.Conversation')),
            ],
        ),
    ]
