# Generated by Django 2.0.5 on 2018-05-29 00:43

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0003_auto_20180528_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
