# Generated by Django 2.0.6 on 2018-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0004_auto_20180529_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created'], 'permissions': (('can_add_promoted', 'Can publish promoted conversations'),)},
        ),
    ]
