# Generated by Django 2.2.19 on 2021-03-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0004_rasaconversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasaconversation',
            options={'ordering': ['-id']},
        ),
    ]
