# Generated by Django 2.0.6 on 2018-06-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0005_auto_20180610_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created'], 'permissions': (('is_publisher', 'Can publish promoted conversations'), ('is_moderator', 'Can moderate comments in any conversation'))},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='question',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(help_text='A short description about this conversations. This is used internally and to create URL slugs. (e.g. School system)', max_length=255, verbose_name='Title'),
        ),
    ]
