# Generated by Django 2.1.10 on 2019-07-17 02:19
import re

import django.core.validators
from django.db import migrations, models

REJECTION_MAP = {
    None: 0,
    "": 0,
    0: 0,
    10: 10,
    20: 20,
    30: 30,
    40: 40,
    50: 50,
    "0": 0,
    "10": 10,
    "20": 20,
    "30": 30,
    "40": 40,
    "50": 50,
    "user_provided": 0,
    "incomplete_text": 10,
    "off_topic": 20,
    "offensive_language": 30,
    "duplicated_comment": 40,
    "against_terms_of_service": 50,
}


def update_rejection_reason(apps, schema_editor):
    Comment = apps.get_model("ej_conversations", "Comment")
    for comment in Comment.objects.all():
        comment.rejection_reason_index = REJECTION_MAP[comment.rejection_reason]
        comment.save()


class Migration(migrations.Migration):
    dependencies = [("ej_conversations", "0005_pre_comment_rejection_reason")]

    operations = [migrations.RunPython(update_rejection_reason)]
