# Generated by Django 2.2.19 on 2021-03-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0005_auto_20210327_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasaconversation',
            options={},
        ),
    ]
