# Generated by Django 2.2.19 on 2021-07-14 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0003_barbara_relax_moderator_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMautic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_name", models.CharField(max_length=100, verbose_name="Mautic username")),
                ("password", models.CharField(max_length=200, verbose_name="Mautic password")),
                (
                    "url",
                    models.URLField(
                        help_text="Generated Url from Mautic.", max_length=255, verbose_name="Mautic URL"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mautic_integration",
                        to="ej_conversations.Conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("conversation", "url")},
            },
        ),
    ]
