# Generated by Django 2.2.19 on 2021-03-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0006_auto_20210330_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rasaconversation',
            options={'ordering': ['-id']},
        ),
    ]
