# Generated by Django 2.0.6 on 2018-07-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0007_auto_20180626_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created'], 'permissions': (('can_publish', 'Can publish promoted conversations'), ('can_moderate', 'Can moderate comments in any conversation'))},
        ),
    ]
