# Generated by Django 2.2.19 on 2021-07-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0006_conversationmautic'),
        ('ej_conversations', '0007_auto_20210330_1605'),
    ]

    operations = [
    ]
