# Generated by Django 2.0.6 on 2018-07-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0007_auto_20180709_1715'),
        ('ej_conversations', '0007_auto_20180625_2340'),
    ]

    operations = [
    ]
