# Generated by Django 2.1.7 on 2019-03-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ej_conversations", "0007_auto_20190305_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
