# Generated by Django 2.2.19 on 2021-08-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ej_conversations", "0008_merge_20210723_1229"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="channel",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("twillio", "Whatsapp"),
                    ("opinion_component", "Opinion Component"),
                    ("socketio", "Rasa webchat"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="From which EJ channel the vote comes from",
                max_length=50,
                verbose_name="Channel",
            ),
        ),
    ]
