# Generated by Django 2.0.7 on 2018-07-30 14:37

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('ej_conversations', '0008_auto_20180722_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_promoted',
            field=models.BooleanField(default=False, help_text='Promoted conversations appears in the main /conversations/ endpoint.', verbose_name='promoted?'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ej_conversations.ConversationTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='favoriteconversation',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='ej_conversations.Conversation'),
        ),
        migrations.AddField(
            model_name='favoriteconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationtag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Conversation'),
        ),
        migrations.AddField(
            model_name='conversationtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ej_conversations_conversationtag_items', to='taggit.Tag'),
        ),
    ]
