# Generated by Django 2.2.19 on 2021-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0008_merge_20210723_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmautic',
            name='password',
        ),
        migrations.RemoveField(
            model_name='conversationmautic',
            name='user_name',
        ),
        migrations.AddField(
            model_name='conversationmautic',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mautic Access Token'),
        ),
        migrations.AddField(
            model_name='conversationmautic',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='conversationmautic',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client Secret'),
        ),
        migrations.AddField(
            model_name='conversationmautic',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='conversationmautic',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Refresh Token'),
        ),
    ]
