# Generated by Django 2.0.6 on 2018-07-23 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_conversations', '0008_auto_20180722_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of an user conversation board.', max_length=140, unique=True, verbose_name='Board name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
