# Generated by Django 2.2.19 on 2021-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0009_auto_20210802_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmautic',
            name='client_id',
            field=models.CharField(max_length=100, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='conversationmautic',
            name='client_secret',
            field=models.CharField(max_length=200, verbose_name='Client Secret'),
        ),
    ]
