# Generated by Django 2.0.7 on 2018-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0008_merge_20180709_1915'),
        ('ej_conversations', '0009_auto_20180730_1437'),
    ]

    operations = [
    ]
