# Generated by Django 2.0.7 on 2018-07-25 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_conversations', '0010_auto_20180724_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationboard',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
