# Generated by Django 2.0.7 on 2018-08-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0010_merge_20180822_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['id']},
        ),
    ]
