# Generated by Django 2.2.19 on 2021-08-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0010_auto_20210804_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmautic',
            name='phone_number',
        ),
    ]
