# Generated by Django 2.2.19 on 2021-08-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0009_vote_channel'),
        ('ej_conversations', '0011_remove_conversationmautic_phone_number'),
    ]

    operations = [
    ]
