# Generated by Django 2.0.7 on 2018-07-25 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0011_conversationboard_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationboard',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
