# Generated by Django 2.2.19 on 2021-09-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0012_merge_20210817_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rasaconversation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rasaconversation',
            name='conversation',
        ),
        migrations.AlterField(
            model_name='vote',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('twilio', 'Whatsapp'), ('rasa', 'RASAX'), ('opinion_component', 'Opinion Component'), ('socketio', 'Rasa webchat'), ('unknown', 'Unknown')], default='unknown', help_text='From which EJ channel the vote comes from', max_length=50, verbose_name='Channel'),
        ),
        migrations.DeleteModel(
            name='ConversationMautic',
        ),
        migrations.DeleteModel(
            name='RasaConversation',
        ),
    ]
