# Generated by Django 2.2.19 on 2021-09-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_boards', '0003_create_default_board'),
        ('ej_conversations', '0013_auto_20210901_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ej_boards.Board'),
        ),
    ]
