# Generated by Django 3.2 on 2021-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0016_conversation_board_update_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='analytics_utm',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
