# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Mulher'), ('MALE', 'Homem'), ('CIS_FEMALE', 'Mulher Cis'), ('CIS_MALE', 'Homem Cis'), ('AGENDER', 'Agênero'), ('GENDERQUEER', 'Genderquer'), ('GENDERFLUID', 'Gênero Fluído'), ('NON-CONFORMIST_GENDER', 'Gênero Não-conformista'), ('VARIANT_GENDER', 'Gênero Variante'), ('INTERSEX', 'Intersex'), ('NON-BINARY', 'Não-binário'), ('TRANSGENDERED', 'Transgênero'), ('PANGENDER', 'Pangênero'), ('TRANSSEXUAL_WOMAN', 'Mulher Transexual'), ('TRANSSEXUAL_MAN', 'Homem Transexual'), ('TRANSFEMINAL', 'Transfeminino'), ('TRANSMASCULINE', 'Transmasculino'), ('DO_NOT_KNOW', 'Não sei'), ('NONE', 'Nenhum'), ('OTHER', 'Outro')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='political_movement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[('BLACK', 'Preta'), ('BROWN', 'Parda'), ('WHITE', 'Branca'), ('YELLOW', 'Amarela'), ('INDIGENOUS', 'Indígena'), ('DO_NOT_KNOW', 'Não sei'), ('UNDECLARED', 'Não declarada')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
