# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171016_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
