# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171016_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('CIS_FEMALE', 'Cis Female'), ('CIS_MALE', 'Cis Male'), ('AGENDER', 'Agender'), ('GENDERQUEER', 'Genderqueer'), ('GENDERFLUID', 'Genderfluid'), ('NON-CONFORMIST_GENDER', 'Non conformist gender'), ('VARIANT_GENDER', 'Variant gender'), ('INTERSEX', 'Intersex'), ('NON-BINARY', 'Non binary'), ('TRANSGENDERED', 'Transgendered'), ('PANGENDER', 'Pangender'), ('TRANSSEXUAL_WOMAN', 'Transsexual woman'), ('TRANSSEXUAL_MAN', 'Transsexual man'), ('TRANSFEMINAL', 'Transfeminal'), ('TRANSMASCULINE', 'Transmasculine'), ('DO_NOT_KNOW', 'Do not know'), ('NONE', 'None'), ('OTHER', 'Other')], max_length=255, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_other',
            field=models.CharField(max_length=255, null=True, verbose_name='Other type of gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=255, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='political_movement',
            field=models.CharField(max_length=255, null=True, verbose_name='Participates in any political movement?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='race',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('WHITE', 'White'), ('YELLOW', 'Yellow'), ('INDIGENOUS', 'Indigenous'), ('DO_NOT_KNOW', 'Do not know'), ('UNDECLARED', 'Undeclared')], max_length=255, null=True, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=255, null=True, verbose_name='State'),
        ),
    ]
