# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171104_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_step',
            field=models.TextField(blank=True, null=True, verbose_name='Current Tour Step'),
        ),
    ]
