# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_tour_default_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tour_step',
            field=models.CharField(blank=True, choices=[('STEP_ONE', 'Step One'), ('STEP_TWO', 'Step Two'), ('STEP_THREE', 'Step Three'), ('STEP_FOUR', 'Step Four'), ('STEP_FIVE', 'Step Five'), ('STEP_SIX', 'Step Six'), ('STEP_SEVEN', 'Step Seven'), ('STEP_EIGHT', 'Step Eight'), ('STEP_NINE', 'Step Nine'), ('STEP_TEN', 'Step Ten'), ('STEP_FINISH', 'Final Step')], max_length=255, null=True, verbose_name='Current tour step'),
        ),
    ]
