# Generated by Django 2.0.8 on 2018-08-04 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RocketChatSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rocketchat_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_access_rocketchat', 'Subscribe to rocket chat.')],
            },
        ),
    ]
