# Generated by Django 2.2.2 on 2019-07-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_rocketchat', '0001_ada_lovelace_v1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcconfig',
            name='admin_password',
        ),
    ]
