# Generated by Django 2.2.3 on 2019-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ej_rocketchat", "0003_barbara_api_url_validator")]

    operations = [
        migrations.AlterField(
            model_name="rcconfig",
            name="admin_token",
            field=models.CharField(
                blank=True,
                help_text="Login token for the Rocket.Chat admin user.",
                max_length=50,
                verbose_name="Login token",
            ),
        )
    ]
