# Generated by Django 2.2.2 on 2019-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_rocketchat', '0003_auto_20190703_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcconfig',
            name='admin_password',
            field=models.CharField(default='password', help_text='Password for the Rocket.Chat admin user.', max_length=50, verbose_name='Admin password'),
            preserve_default=False,
        ),
    ]
