# Generated by Django 2.2.3 on 2019-08-05 02:47

from django.db import migrations, models
import ej_rocketchat.validators


class Migration(migrations.Migration):

    dependencies = [("ej_rocketchat", "0004_barbara_make_admin_token_optional")]

    operations = [
        migrations.AlterField(
            model_name="rcconfig",
            name="admin_password",
            field=models.CharField(
                blank=True,
                help_text="Password for the Rocket.Chat admin user.",
                max_length=50,
                validators=[ej_rocketchat.validators.requires_setup_for_blank],
                verbose_name="Admin password",
            ),
        ),
        migrations.AlterField(
            model_name="rcconfig",
            name="api_url",
            field=models.CharField(
                blank=True,
                help_text="A private URL used only for API calls. Can be used to override the public URL if Rocket.Chat is also available from an internal address in your network.",
                max_length=200,
                null=True,
                validators=[ej_rocketchat.validators.WhiteListedURLValidator()],
                verbose_name="Rocket.Chat private URL",
            ),
        ),
        migrations.AlterField(
            model_name="rcconfig",
            name="url",
            field=models.URLField(
                default="http://localhost:3000",
                help_text="Public URL in which the Rocket.Chat instance is installed.",
                verbose_name="Rocket.Chat URL",
            ),
        ),
    ]
