# Generated by Django 2.0.6 on 2018-06-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['id']},
        ),
    ]
