# Generated by Django 2.0.6 on 2018-06-22 18:56

from django.db import migrations, models
import ej_missions.models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0003_auto_20180621_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='fileUpload',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/default.jpg', upload_to=ej_missions.models.mission_directory_path),
        ),
        migrations.AddField(
            model_name='mission',
            name='youtubeVideo',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
