# Generated by Django 2.0.6 on 2018-06-22 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_missions', '0004_auto_20180622_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('userEmail', models.CharField(max_length=60)),
                ('satus', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('receiptFile', models.FileField(default='/home2/david/projects/ej-server/local/media/uploads/default.jpg', upload_to='uploads')),
            ],
        ),
        migrations.AlterField(
            model_name='mission',
            name='fileUpload',
            field=models.FileField(default='/home2/david/projects/ej-server/local/media/uploads/default.jpg', upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_missions.Mission'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
