# Generated by Django 2.0.6 on 2018-06-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0005_auto_20180622_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='satus',
            new_name='status',
        ),
    ]
