# Generated by Django 2.0.6 on 2018-06-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0008_auto_20180625_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='fileUpload',
            field=models.FileField(default='default.jpg', upload_to='missions'),
        ),
    ]
