# Generated by Django 2.0.6 on 2018-06-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0010_mission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='user',
            new_name='owner',
        ),
    ]
