# Generated by Django 2.0.6 on 2018-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0011_auto_20180626_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='fileUpload',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='missions'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='youtubeVideo',
            field=models.CharField(default='', max_length=60),
        ),
    ]
