# Generated by Django 2.0.6 on 2018-06-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0012_auto_20180626_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
