# Generated by Django 2.0.6 on 2018-06-27 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0013_auto_20180626_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
