# Generated by Django 2.0.6 on 2018-06-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0014_auto_20180627_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='youtubeVideo',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
