# Generated by Django 2.0.6 on 2018-06-27 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0015_auto_20180627_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='youtubeVideo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
