# Generated by Django 2.0.6 on 2018-06-27 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0016_auto_20180627_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
