# Generated by Django 2.0.6 on 2018-06-27 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0017_auto_20180627_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
