# Generated by Django 2.0.6 on 2018-06-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0018_auto_20180627_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='deadline',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
