# Generated by Django 2.0.6 on 2018-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0019_mission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
