# Generated by Django 2.0.6 on 2018-07-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0023_auto_20180704_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='reward',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
