# Generated by Django 2.0.6 on 2018-07-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_trophies', '0005_auto_20180704_1950'),
        ('ej_missions', '0024_mission_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='trophy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ej_trophies.Trophy'),
        ),
    ]
