# Generated by Django 2.0.6 on 2018-07-20 14:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0025_mission_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='reward',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
