# Generated by Django 2.0.6 on 2018-07-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0008_merge_20180709_1915'),
        ('ej_missions', '0026_auto_20180720_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='conversations',
            field=models.ManyToManyField(blank=True, to='ej_conversations.Conversation'),
        ),
    ]
