ARG BASE=buster

FROM ejplatform/python:${BASE}
ARG INSTALL=local

# Install Python dependencies
COPY "./requirements-${INSTALL}.txt" requirements.txt
COPY "./requirements-local.txt" local.txt
RUN pip install -r requirements.txt \
 && rm -rf /root/.cache/*
