FROM ejplatform/python:test as testpackages
FROM ejplatform/tools:latest

# Install Python dependencies
COPY --from=testpackages /pypackages /pypackages

# Set environment variables in order for this to work :)
ENV PATH=$PATH:/pypackages/bin
ENV PYTHON=$PYTHONPATH:/pypackages/lib/python3.6/site-packages

# We clone hyperpython and django boogie in /app/local/vendor/ in order to make
# the updates to the dev image faster
WORKDIR /app
RUN mkdir -p /app/local/vendor/ \
 && git clone --depth=1 \
        https://github.com/fabiommendes/hyperpython.git \
        /app/local/vendor/hyperpython \
 && git clone --depth=1 \
        https://github.com/fabiommendes/django-boogie.git \
        /app/local/vendor/django-boogie \
 && cd /app/local/vendor/django-boogie/ && python setup.py develop \
 && cd /app/local/vendor/hyperpython/ && python setup.py develop \
 && echo "ENDING CLONING REPOSITORIES"
