FROM ejplatform/python:buster

# Install Python dependencies
COPY "./requirements-production.txt" requirements.txt
COPY "./requirements-local.txt" local.txt
RUN pip install -r requirements.txt \
 && rm -rf /root/.cache/*
