# Generated by Django 2.0.5 on 2018-06-06 14:16

import boogie.fields.enum_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ej_conversations.models.vote
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_conversations', '0004_auto_20180529_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='ej_conversations.Conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stereotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='StereotypeClusterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_clusters.Cluster')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Conversation')),
                ('stereotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_clusters.Stereotype')),
            ],
        ),
        migrations.CreateModel(
            name='StereotypeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', boogie.fields.enum_field.EnumField(ej_conversations.models.vote.Choice)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ej_clusters.Stereotype')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stereotype_votes', to='ej_conversations.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='UserClusterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_clusters.Cluster')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_conversations.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='stereotypes',
            field=models.ManyToManyField(through='ej_clusters.StereotypeClusterMap', to='ej_clusters.Stereotype'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(through='ej_clusters.UserClusterMap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userclustermap',
            unique_together={('user', 'conversation')},
        ),
        migrations.AlterUniqueTogether(
            name='stereotypeclustermap',
            unique_together={('stereotype', 'conversation')},
        ),
    ]
