# Generated by Django 2.0.6 on 2018-06-11 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clusterization',
            options={'ordering': ['conversation_id']},
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='clusters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clusterization',
            name='unprocessed_comments',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clusterization',
            name='unprocessed_votes',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='stereotype',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of your stereotype for future reference. You can specify a background history, or give hints on the exact profile the stereotype wants to capture.', verbose_name='Description'),
        ),
    ]
