# Generated by Django 2.2.2 on 2019-06-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ej_conversations", "0001_initial"),
        ("ej_clusters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stereotypevote",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stereotype_votes",
                to="ej_conversations.Comment",
                verbose_name="Comment",
            ),
        )
    ]
