# Generated by Django 2.0.8 on 2019-06-26 19:11

from autoslug import AutoSlugField
from django.db import migrations, models
import django.db.models.deletion
from ej_clusters.models import Cluster

def migrate_data_forward(apps, schema_editor):
    for instance in Cluster.objects.all():
        print("Generating slug for ", instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0001_first_migration'),
        ('ej_clusters', '0002_update_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='slug',
            field=AutoSlugField(null=True, default=None, editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        )
    ]
