# Generated by Django 2.0.6 on 2018-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0002_auto_20180611_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='description',
            field=models.TextField(blank=True, help_text='How was this cluster conceived?', verbose_name='Description'),
        ),
    ]
