# Generated by Django 2.2.3 on 2019-08-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ej_clusters", "0002_barbara_rc1")]

    operations = [
        migrations.RemoveField(model_name="clusterization", name="pending_comments"),
        migrations.RemoveField(model_name="clusterization", name="pending_votes"),
    ]
