# Generated by Django 2.1.3 on 2018-12-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0003_update_field_clusterization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stereotype',
            name='conversation',
        ),
    ]
