# Generated by Django 2.0.7 on 2018-08-06 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_clusters', '0003_cluster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stereotype',
            name='owner',
            field=models.ForeignKey(default=0, help_text='Only the owner and administrative staff can edit this stereotype.', on_delete=django.db.models.deletion.CASCADE, related_name='stereotypes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
