# Generated by Django 2.0.7 on 2018-08-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0005_auto_20180814_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stereotype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
