# Generated by Django 2.0.7 on 2018-08-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0006_auto_20180822_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stereotype',
            name='owner',
        ),
    ]
