# Generated by Django 2.0.6 on 2018-08-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_clusters', '0007_auto_20180814_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stereotype',
            name='owner',
        ),
    ]
