# Generated by Django 2.2.2 on 2019-06-04 21:14

import boogie.fields.enum_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import ej_gamification.enums
import ej_gamification.models.given_powers
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ej_conversations', '0006_auto_20190604_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('score_bias', models.SmallIntegerField(default=0)),
                ('commenter_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.CommenterLevel, default=ej_gamification.enums.CommenterLevel(0))),
                ('max_commenter_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.CommenterLevel, default=ej_gamification.enums.CommenterLevel(0))),
                ('host_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.HostLevel, default=ej_gamification.enums.HostLevel(0))),
                ('max_host_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.HostLevel, default=ej_gamification.enums.HostLevel(0))),
                ('profile_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.ProfileLevel, default=ej_gamification.enums.ProfileLevel(0))),
                ('max_profile_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.ProfileLevel, default=ej_gamification.enums.ProfileLevel(0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User progress list',
            },
        ),
        migrations.CreateModel(
            name='ParticipationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('score_bias', models.SmallIntegerField(default=0)),
                ('voter_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.VoterLevel, default=ej_gamification.enums.VoterLevel(0))),
                ('max_voter_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.VoterLevel, default=ej_gamification.enums.VoterLevel(0))),
                ('is_owner', models.BooleanField(default=False)),
                ('is_focused', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_progresses', to='ej_conversations.Conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GivenPower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_powers', to='ej_conversations.Conversation')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ej_gamification.givenpower_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_powers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('message', models.TextField(blank=True, help_text='Optional message explaining why the endorsement affected the given set of users.', verbose_name='Endorsement reason')),
                ('is_global', models.BooleanField(default=False, help_text='Global comments affect all users in conversation', verbose_name='Is it global?')),
                ('affected_users', models.ManyToManyField(blank=True, related_name='affecting_endorsements', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='ej_conversations.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('score_bias', models.SmallIntegerField(default=0)),
                ('conversation_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.ConversationLevel, default=ej_gamification.enums.CommenterLevel(0))),
                ('max_conversation_level', boogie.fields.enum_field.EnumField(ej_gamification.enums.ConversationLevel, default=ej_gamification.enums.CommenterLevel(0))),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='ej_conversations.Conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation progress list',
            },
        ),
        migrations.CreateModel(
            name='GivenBridgePower',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ej_gamification.models.given_powers.EndorsementPowerMixin, 'ej_gamification.givenpower'),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GivenMinorityPower',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ej_gamification.models.given_powers.EndorsementPowerMixin, 'ej_gamification.givenpower'),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
