# Generated by Django 2.2.3 on 2019-07-28 02:09

import boogie.fields.enum_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ej_gamification.enums


class Migration(migrations.Migration):

    dependencies = [("ej_gamification", "0001_barbara_rc1")]

    operations = [
        migrations.AlterModelOptions(
            name="conversationprogress",
            options={"verbose_name": "Conversation score", "verbose_name_plural": "Conversation scores"},
        ),
        migrations.AlterModelOptions(
            name="endorsement",
            options={"verbose_name": "Endorsement", "verbose_name_plural": "Endorsements"},
        ),
        migrations.AlterModelOptions(
            name="givenpower",
            options={"verbose_name": "Given Power", "verbose_name_plural": "Given Powers"},
        ),
        migrations.AlterModelOptions(
            name="participationprogress",
            options={
                "verbose_name": "User score (per conversation)",
                "verbose_name_plural": "User scores (per conversation)",
            },
        ),
        migrations.AlterModelOptions(
            name="userprogress",
            options={"verbose_name": "User score", "verbose_name_plural": "User scores"},
        ),
        migrations.AlterField(
            model_name="conversationprogress",
            name="conversation_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.ConversationLevel,
                default=ej_gamification.enums.CommenterLevel(0),
                help_text="Measures the level of engagement for conversation.",
                verbose_name="conversation level",
            ),
        ),
        migrations.AlterField(
            model_name="conversationprogress",
            name="max_conversation_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.ConversationLevel,
                default=ej_gamification.enums.CommenterLevel(0),
                editable=False,
                help_text="maximum achieved conversation level",
            ),
        ),
        migrations.AlterField(
            model_name="conversationprogress",
            name="score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="conversationprogress",
            name="score_bias",
            field=models.SmallIntegerField(
                default=0,
                help_text="Artificially increase score for any reason",
                verbose_name="score adjustment",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="conversation",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_progresses",
                to="ej_conversations.Conversation",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="is_focused",
            field=models.BooleanField(
                default=False,
                help_text="User received a focused badge (i.e., voted on all comments)",
                verbose_name="focused?",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="is_owner",
            field=models.BooleanField(
                default=False,
                help_text="Total score is computed differently if user owns conversation.",
                verbose_name="owner?",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="max_voter_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.VoterLevel,
                default=ej_gamification.enums.VoterLevel(0),
                editable=False,
                verbose_name="maximum achieved voter level",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="score_bias",
            field=models.SmallIntegerField(
                default=0,
                help_text="Artificially increase score for any reason",
                verbose_name="score adjustment",
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_progresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="participationprogress",
            name="voter_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.VoterLevel,
                default=ej_gamification.enums.VoterLevel(0),
                help_text="Measure how many votes user has given in conversation",
                verbose_name="voter level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="commenter_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.CommenterLevel,
                default=ej_gamification.enums.CommenterLevel(0),
                help_text="Measures how much user participated by contributing comments to conversations",
                verbose_name="commenter level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="host_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.HostLevel,
                default=ej_gamification.enums.HostLevel(0),
                help_text="Measures how much user participated by creating engaging conversations.",
                verbose_name="host level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="max_commenter_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.CommenterLevel,
                default=ej_gamification.enums.CommenterLevel(0),
                editable=False,
                verbose_name="maximum achieved commenter level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="max_host_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.HostLevel,
                default=ej_gamification.enums.HostLevel(0),
                editable=False,
                verbose_name="maximum achieved host level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="max_profile_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.ProfileLevel,
                default=ej_gamification.enums.ProfileLevel(0),
                editable=False,
                verbose_name="maximum achieved profile level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="profile_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.ProfileLevel,
                default=ej_gamification.enums.ProfileLevel(0),
                help_text="Measures how complete is the user profile.",
                verbose_name="profile level",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="score"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="score_bias",
            field=models.SmallIntegerField(
                default=0,
                help_text="Artificially increase score for any reason",
                verbose_name="score adjustment",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
