# Generated by Django 2.2.19 on 2021-03-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_gamification', '0002_barbara_update_field_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationprogress',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='participationprogress',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.SmallIntegerField(default=0, verbose_name='score'),
        ),
    ]
