# Generated by Django 2.1.7 on 2019-03-11 13:36

import boogie.fields.enum_field
from django.db import migrations
import ej_gamification.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ej_gamification', '0004_auto_20190311_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationprogress',
            name='voter_level',
            field=boogie.fields.enum_field.EnumField(ej_gamification.enums.VoterLevel, default=ej_gamification.enums.VoterLevel(0)),
        ),
    ]
