# Generated by Django 2.1.7 on 2019-03-16 22:00

import boogie.fields.enum_field
from django.db import migrations
import ej_gamification.enums


class Migration(migrations.Migration):

    dependencies = [("ej_gamification", "0006_auto_20190311_1342")]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="max_commenter_level",
            field=boogie.fields.enum_field.EnumField(
                ej_gamification.enums.CommenterLevel,
                default=ej_gamification.enums.CommenterLevel(0),
            ),
        )
    ]
