# Generated by Django 2.1.7 on 2019-03-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0013_auto_20190310_2215'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ej_gamification', '0008_auto_20190316_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('message', models.TextField(blank=True, help_text='Optional message explaining why the endorsement affected the given set of users.', verbose_name='Endorsement reason')),
                ('is_global', models.BooleanField(default=False, help_text='Global comments affect all users in conversation', verbose_name='Is it global?')),
                ('affected_users', models.ManyToManyField(blank=True, related_name='affecting_endorsements', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='ej_conversations.Comment')),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_endorsements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
