# Generated by Django 2.1.10 on 2019-07-02 16:13

import boogie.fields.enum_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ej_profiles.enums


class Migration(migrations.Migration):

    replaces = [
        ("ej_profiles", "0001_first_migration"),
        ("ej_profiles", "0002_add_state_field"),
        ("ej_profiles", "0003_update_image_field"),
    ]

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "race",
                    boogie.fields.enum_field.EnumField(
                        ej_profiles.enums.Race, default=ej_profiles.enums.Race(0), verbose_name="Race"
                    ),
                ),
                ("ethnicity", models.CharField(blank=True, max_length=50, verbose_name="Ethnicity")),
                ("education", models.CharField(blank=True, max_length=140, verbose_name="Education")),
                (
                    "gender",
                    boogie.fields.enum_field.EnumField(
                        ej_profiles.enums.Gender,
                        default=ej_profiles.enums.Gender(0),
                        verbose_name="Gender identity",
                    ),
                ),
                (
                    "gender_other",
                    models.CharField(blank=True, max_length=50, verbose_name="User provided gender"),
                ),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="Birth Date")),
                ("country", models.CharField(blank=True, max_length=50, verbose_name="Country")),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="State",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=140, verbose_name="City")),
                ("biography", models.TextField(blank=True, verbose_name="Biography")),
                ("occupation", models.CharField(blank=True, max_length=50, verbose_name="Occupation")),
                ("political_activity", models.TextField(blank=True, verbose_name="Political activity")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images", verbose_name="Profile Photo"
                    ),
                ),
            ],
            options={"ordering": ["user__email"]},
        )
    ]
