# Generated by Django 2.2.3 on 2019-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ej_profiles", "0002_barbara_rc1")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=3, verbose_name="State"),
        )
    ]
