# Generated by Django 2.0.5 on 2018-06-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0003_auto_20180529_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
