# Generated by Django 2.0.6 on 2018-07-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0004_auto_20180606_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__email']},
        ),
    ]
