# Generated by Django 2.0.6 on 2018-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0004_auto_20180606_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Age'),
        ),
    ]
