# Generated by Django 3.2 on 2022-01-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0004_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_tour',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
