# Generated by Django 2.0.8 on 2018-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0005_auto_20180725_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
    ]
