# Generated by Django 2.0.6 on 2018-07-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0006_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_notifications', models.BooleanField(default=True)),
                ('conversation_notifications', models.BooleanField(default=True)),
                ('admin_notifications', models.BooleanField(default=True)),
                ('trophy_notifications', models.BooleanField(default=True)),
                ('campaign_email', models.BooleanField(default=True)),
                ('campaign_app_notifications', models.BooleanField(default=True)),
                ('share_data', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej_profiles.Profile')),
            ],
        ),
    ]
