# Generated by Django 2.0.8 on 2018-08-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0006_auto_20180807_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=140, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ethnicity'),
        ),
    ]
