# Generated by Django 2.0.6 on 2018-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0008_auto_20180719_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
