# Generated by Django 2.0.6 on 2018-07-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0009_setting_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='approved_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='disapproved_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
