# Generated by Django 2.0.7 on 2018-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_profiles', '0010_auto_20180722_2054'),
        ('ej_profiles', '0007_auto_20180808_0015'),
    ]

    operations = [
    ]
