# Generated by Django 2.0.6 on 2018-07-24 14:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ej_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='channel',
            name='sort',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
