# Generated by Django 2.0.6 on 2018-07-24 17:49

from django.db import migrations

def create_channels(apps, schema_editor):
    Channel = apps.get_model("ej_channels", "Channel")
    channel_1 = Channel(id=1, name="admin channel", sort="admin")
    channel_1.save()
    channel_2 = Channel(id=2, name="mission channel", sort="mission")
    channel_2.save()



class Migration(migrations.Migration):

    dependencies = [
        ('ej_channels', '0002_auto_20180724_1403'),
    ]

    operations = [
        migrations.RunPython(create_channels),
    ]
