# Generated by Django 2.0.6 on 2018-07-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_channels', '0004_channel_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['id']},
        ),
    ]
